package infotainment.presenter;

import java.util.TimerTask;

import infotainment.Model.db.Db;

public class rpmtimertask extends TimerTask
{

    public rpmtimertask()
    {
        int newRPM = RpmGenerator.rndInt()
    }

    @Override
    public void run()
    {
        int value = 0; /* TODO Generated by rndInt() later on /

        /* Pass value to inputfilter along with tag */
        char tag = Db.EntryType.RPM;

        /* Pass value to other sources */
    }

}